apiVersion: v1
kind: Pod
metadata:
  name: compile-server-2
  labels:
    app: compile-server-2
spec:
  containers:
  - name: compile-server-2
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 8.8.8.8
